import * as THREE from './assets/three.module.js';

const prefersReduced=matchMedia('(prefers-reduced-motion: reduce)');
const state={paused:prefersReduced.matches,quality:'full',drag:null};
const byId=id=>document.getElementById(id);
function dispatch(name,detail={}){window.dispatchEvent(new CustomEvent(name,{detail}))}

function starfield(){
 const canvas=byId('starfield'),ctx=canvas.getContext('2d');let w=0,h=0,dpr=1,stars=[];
 function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);stars=Array.from({length:Math.min(420,Math.floor(w/3))},()=>({x:Math.random()*w,y:Math.random()*h,z:Math.random(),r:.35+Math.random()*1.6,phase:Math.random()*Math.PI*2,tw:1+Math.random()*3,drift:(Math.random()-.5)*.14}))}
 function draw(t){ctx.clearRect(0,0,w,h);for(const s of stars){if(!state.paused){s.y+=.04+s.z*.22;s.x+=s.drift;if(s.y>h+5)s.y=-4;if(s.x>w+5)s.x=-4;if(s.x< -5)s.x=w+4}const pulse=.55+.45*Math.sin(t*.001*s.tw+s.phase),a=(.14+s.z*.8)*pulse;ctx.beginPath();ctx.arc(s.x,s.y,s.r*(.7+s.z),0,Math.PI*2);ctx.fillStyle=`rgba(${120+Math.round(s.z*100)},${170+Math.round(s.z*80)},255,${a})`;ctx.fill();if(s.z>.82&&pulse>.93){ctx.strokeStyle=`rgba(210,235,255,${a*.45})`;ctx.lineWidth=.5;ctx.beginPath();ctx.moveTo(s.x-5,s.y);ctx.lineTo(s.x+5,s.y);ctx.moveTo(s.x,s.y-5);ctx.lineTo(s.x,s.y+5);ctx.stroke()}}requestAnimationFrame(draw)}
 addEventListener('resize',resize);resize();requestAnimationFrame(draw);
}
function makeRenderer(stage){
 try{const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.75));renderer.setClearColor(0x000000,0);stage.replaceChildren(renderer.domElement);return renderer}catch(e){stage.innerHTML='<div class="model-fallback">WebGL is unavailable in this browser.<br>Use the motion controls and the crew archive below to explore SFS.</div>';return null}
}
function addGlowSprite(scene,color,size,opacity=.5){const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const c=canvas.getContext('2d'),g=c.createRadialGradient(64,64,0,64,64,64);const col=new THREE.Color(color),r=Math.round(col.r*255),gg=Math.round(col.g*255),b=Math.round(col.b*255);g.addColorStop(0,`rgba(${r},${gg},${b},${opacity})`);g.addColorStop(.3,`rgba(${r},${gg},${b},${opacity*.35})`);g.addColorStop(1,'rgba(0,0,0,0)');c.fillStyle=g;c.fillRect(0,0,128,128);const tex=new THREE.CanvasTexture(canvas),mat=new THREE.SpriteMaterial({map:tex,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending});const s=new THREE.Sprite(mat);s.scale.set(size,size,1);scene.add(s);return s}
function hero(){const stage=byId('heroStage');if(!stage)return;const renderer=makeRenderer(stage);if(!renderer)return;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(45,1,.1,100);camera.position.set(0,0,8);scene.add(new THREE.AmbientLight(0x7997ff,1.4));const key=new THREE.PointLight(0x8be9ff,18,20);key.position.set(2,2,4);scene.add(key);const warm=new THREE.PointLight(0xffa36b,12,15);warm.position.set(-3,-2,2);scene.add(warm);
 const machine=new THREE.Group();scene.add(machine);const core=new THREE.Mesh(new THREE.IcosahedronGeometry(1.05,4),new THREE.MeshPhysicalMaterial({color:0x80e9ff,emissive:0x2355a0,emissiveIntensity:1.7,metalness:.25,roughness:.18,transmission:.15,thickness:.6}));machine.add(core);addGlowSprite(machine,0x72dfff,3.4,.55);
 const torusMats=[0x91ecff,0xcc8eff,0xf6c59a,0x7c94ff,0xb4faff];[1.55,1.85,2.2,2.55,2.9].forEach((r,i)=>{const ring=new THREE.Mesh(new THREE.TorusGeometry(r,.026+(i%2)*.018,8,160),new THREE.MeshBasicMaterial({color:torusMats[i],transparent:true,opacity:.72,blending:THREE.AdditiveBlending}));ring.rotation.set(i*.22,(i%2)*.55,Math.PI/2+i*.1);ring.userData.spin=(i%2?-1:1)*(.12+i*.025);machine.add(ring)});
 const shards=new THREE.Group();machine.add(shards);for(let i=0;i<80;i++){const m=new THREE.Mesh(new THREE.OctahedronGeometry(.025+Math.random()*.05,0),new THREE.MeshBasicMaterial({color:i%3?0x9fddff:0xe0afff,transparent:true,opacity:.8}));const a=Math.random()*Math.PI*2,r=2.7+Math.random()*2.1;m.position.set(Math.cos(a)*r,(Math.random()-.5)*2.4,Math.sin(a)*r);m.userData.a=a;m.userData.r=r;m.userData.s=.2+Math.random()*.5;shards.add(m)}
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let drag=null,rotX=0,rotY=0;stage.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,rx:rotX,ry:rotY};stage.setPointerCapture(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!drag)return;rotY=drag.ry+(e.clientX-drag.x)*.008;rotX=drag.rx+(e.clientY-drag.y)*.004});stage.addEventListener('pointerup',()=>drag=null);stage.addEventListener('click',e=>{if(!drag||Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<8){const r=stage.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);if(ray.intersectObject(core,true).length){dispatch('sfs:discover',{id:'core'});dispatch('sfs:hero-core')}}drag=null});
 function resize(){const r=stage.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
 function frame(t){if(!state.paused){machine.rotation.y+=.0018;machine.rotation.x+=(rotX-machine.rotation.x)*.035;machine.rotation.z+=(rotY-machine.rotation.z)*.035;machine.children.forEach((o,i)=>{if(o.userData.spin)o.rotation.z+=o.userData.spin*.008});shards.rotation.y-=.001;shards.children.forEach(s=>{s.userData.a+=.002*s.userData.s;s.position.x=Math.cos(s.userData.a)*s.userData.r;s.position.z=Math.sin(s.userData.a)*s.userData.r;s.rotation.x+=.01})}renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame)
}
function crew(){const stage=byId('crewStage');if(!stage)return;const renderer=makeRenderer(stage);if(!renderer)return;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.1,100);camera.position.set(0,0,11);scene.add(new THREE.AmbientLight(0x88aaff,1.2));const light=new THREE.PointLight(0xb8ecff,18,30);light.position.set(0,2,5);scene.add(light);const warm=new THREE.PointLight(0xe79aff,12,25);warm.position.set(-3,-3,1);scene.add(warm);const galaxy=new THREE.Group();scene.add(galaxy);
 const sun=new THREE.Mesh(new THREE.IcosahedronGeometry(1.05,4),new THREE.MeshPhysicalMaterial({color:0xb89cff,emissive:0x4f37aa,emissiveIntensity:2.2,roughness:.2,metalness:.25}));galaxy.add(sun);addGlowSprite(galaxy,0xa994ff,3,.55);
 const orbitGroups=[];const crew=[['kaves.webp',0x7beaff],['hudson.webp',0xffd49d],['manish.webp',0xa99cff],['zohaib.webp',0x85ffc7],['saksham.webp',0xff9bdd]];const loader=new THREE.TextureLoader();
 crew.forEach(([file,color],i)=>{const g=new THREE.Group();g.rotation.set((i-2)*.12,i*.18,(i%2?-1:1)*.3);const ring=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(Array.from({length:96},(_,n)=>{const a=n/96*Math.PI*2;return new THREE.Vector3(Math.cos(a)*(2.0+i*.34),Math.sin(a)*(1.0+i*.12),0)})),new THREE.LineBasicMaterial({color,transparent:true,opacity:.33}));g.add(ring);const satellite=new THREE.Group();const body=new THREE.Mesh(new THREE.DodecahedronGeometry(.35,1),new THREE.MeshPhysicalMaterial({color,emissive:color,emissiveIntensity:.7,metalness:.55,roughness:.25}));satellite.add(body);const halo=new THREE.Mesh(new THREE.TorusGeometry(.53,.018,6,64),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8}));halo.rotation.x=Math.PI/2;satellite.add(halo);const photo=loader.load('assets/'+file);const plane=new THREE.Mesh(new THREE.PlaneGeometry(.42,.55),new THREE.MeshBasicMaterial({map:photo,transparent:true,side:THREE.DoubleSide}));plane.position.z=.38;satellite.add(plane);satellite.position.set(2.0+i*.34,0,0);g.add(satellite);g.userData={satellite,angle:i*1.22,speed:.15+i*.025};galaxy.add(g);orbitGroups.push(g)});
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();stage.addEventListener('click',e=>{const r=stage.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(orbitGroups.map(g=>g.userData.satellite),true);if(hits.length){let picked=orbitGroups.findIndex(g=>g.userData.satellite===hits[0].object||g.userData.satellite.children.includes(hits[0].object));if(picked>=0){dispatch('sfs:crew-select',{index:picked});document.querySelector(`[data-crew-select="${picked}"]`)?.click()}}});let drag=null,spin=0;stage.addEventListener('pointerdown',e=>{drag={x:e.clientX,spin};stage.setPointerCapture(e.pointerId)});stage.addEventListener('pointermove',e=>{if(drag)spin+=(e.clientX-drag.x)*.004});stage.addEventListener('pointerup',()=>drag=null);
 function resize(){const r=stage.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();function frame(t){if(!state.paused){galaxy.rotation.y+=.0008+spin*.001;spin*=.98;orbitGroups.forEach((g,i)=>{g.userData.angle+=.003*g.userData.speed;const a=g.userData.angle;g.userData.satellite.position.x=Math.cos(a)*(2+i*.34);g.userData.satellite.position.y=Math.sin(a)*(1+i*.12);g.userData.satellite.rotation.y+=.01;g.userData.satellite.rotation.z+=.005})}renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);addEventListener('sfs:crew-pause',e=>{state.paused=e.detail.paused});addEventListener('sfs:crew-select',e=>{orbitGroups.forEach((g,i)=>{const on=i===e.detail.index;g.scale.setScalar(on?1.13:1);g.children[0].material.opacity=on?.65:.33})})
}
addEventListener('sfs:motion',e=>{state.paused=e.detail.paused});
starfield();hero();crew();prefersReduced.addEventListener('change',e=>{state.paused=e.matches});
